<?php

/**
 * @file
 * Provides custom <item> elements for Views RSS module.
 */

/**
 * Implements hook_views_rss_namespaces().
 */
function views_rss_custom_views_rss_namespaces() {
  return array();
}

/**
 * Implements hook_views_rss_item_elements().
 */
function views_rss_custom_views_rss_item_elements() {
  $elements['custom:author'] = array(
    'key' => 'author',
    'description' => t('An HTML with \<h3 class="text-signature"\> element to extract the author name.'),
    'preprocess functions' => array('views_rss_custom_preprocess_item_custom_author'),
  );

  return $elements;
}

/**
 * Preprocess function for item <author> element.
 */
function views_rss_custom_preprocess_item_custom_author(&$variables) {
  // No value = no preprocessing.
  if (empty($variables['elements'][0]['value'])) {
    return;
  }

  // Process content
  $html = new simple_html_dom();
  $html->load($variables['elements'][0]['value']);

  $author_html = $html->find('h3[class=text-signature]', -1);

  $variables['elements'][0]['key'] = 'author';
  if (!isset($author_html)) {
    $variables['elements'][0]['value'] = NULL;
  }
  $variables['elements'][0]['value'] = $author_html->plaintext;
}
