<?php 

/**
* Implements hook_help.
*
* Displays help and module information.
*
* @param path 
*   Which path of the site we're using to display help
* @param arg
*   Array that holds the current path as returned from arg() function
*/

function help_ads_help($path, $arg) {
   switch ($path) {
     case "admin/help#help_ads":
       return '<p>' . t("Shows help link on ads form page") . '</p>';
       break;
   }
}

function help_ads_theme($existing, $type, $theme, $path) {
    return array(
        'ads_node_form' => array(
            'arguments' => array('form' => null),
            'path' => drupal_get_path('theme', 'dev').'/templates/forms',
            'template' => 'ads--node-form', 
            'render element' => 'form'
        )
    );
}
