<?php

/**
 * @file
 * Provides Yandex.Zen <item> elements for Views RSS module.
 */

/**
 * Implements hook_views_rss_item_elements().
 */
function views_rss_yandex_zen_views_rss_item_elements() {
  $elements['zen:author'] = array(
    'description' => t('An HTML with h3 class="text-signature" element to extract the author name from.'),
    'preprocess functions' => array('views_rss_yandex_zen_preprocess_item_custom_author'),
  );
  $elements['zen:enclosure'] = array(
    'description' => t('The node content to extract enclosures from.'),
    'help' => 'https://yandex.ru/support/zen/website/rss-modify.html',
    'preprocess functions' => array(
      'views_rss_custom_rewrite_absolute_paths',
      'views_rss_yandex_zen_preprocess_item_zen_enclosure',
    ),
  );
  $elements['zen:content:encoded'] = array(
    'description' => t('The node content to extract enclosures from.'),
    'help' => 'https://yandex.ru/support/zen/website/rss-modify.html',
    'preprocess functions' => array(
      'views_rss_yandex_zen_preprocess_item_zen_content_encoded',
      'views_rss_custom_rewrite_absolute_paths',
      'views_rss_custom_encode',
    ),
  );

  return $elements;
}

/**
 * Preprocess function for item <author> element.
 */
function views_rss_yandex_zen_preprocess_item_custom_author(&$variables) {
  // No value = no preprocessing.
  if (empty($variables['elements'][0]['value'])) {
    return;
  }

  $variables['elements'][0]['key'] = 'author';
  $default_author = 'horki.info';
  $max_length = 60;

  // Process content
  $html = new simple_html_dom();
  $html->load($variables['elements'][0]['value']);
  // Extract author name from content
  $author_html = $html->find('h3[class=text-signature]', -1);
  if (!isset($author_html)) {
    $variables['elements'][0]['value'] = $default_author;
    return;
  }
  $author = $author_html->plaintext;
  if (mb_strlen($author) > $max_length) {
    // Seems like not an author name
    $variables['elements'][0]['value'] = $default_author;
    return;
  }
  $variables['elements'][0]['value'] = $author;
}

/**
 * Preprocess function for item <enclosure> element.
 */
function views_rss_yandex_zen_preprocess_item_zen_enclosure(&$variables) {
  // No value = no preprocessing.
  if (empty($variables['elements'][0]['value'])) {
    return;
  }

  // Process content
  $html = new simple_html_dom();
  $html->load($variables['elements'][0]['value']);
  // Extract image data from content
  $imgs = $html->find('img');
  if (empty($imgs)) {
    $variables['elements'][0]['value'] = NULL;
    return;
  }
  $img_urls = array();
  foreach ($imgs as $idx => $img) {
    $img_url = NULL;
    // Locate image URL
    if (isset($img->src)) {
      $img_url = $img->src;
    } else if (isset($img->srcset)) {
      $img_url = $img->srcset;
    } else if ($img->hasAttribute('data-srcset')) {
      $img_url = $img->getAttribute('data-srcset');
    } else {
      continue;
    }
    // Remove url parameters from src
    $img_urls[] = strtok($img_url, '?');
  }
  // Remove duplicates
  $unique_img_urls = array_unique($img_urls);
  foreach ($unique_img_urls as $idx => $img_url) {
    $variables['elements'][$idx]['key'] = 'enclosure';
    $variables['elements'][$idx]['attributes']['url'] = $img_url;
    $variables['elements'][$idx]['attributes']['type'] = 'image/jpeg';
    $variables['elements'][$idx]['value'] = NULL;
  }
}

function views_rss_yandex_zen_preprocess_item_zen_content_encoded(&$variables) {
  // No value = no preprocessing.
  if (empty($variables['elements'][0]['value'])) {
    return;
  }

  // Process content
  $html = new simple_html_dom();
  $html->load($variables['elements'][0]['value']);
  // Process images
  foreach ($html->find('img') as $img) {
    $img->width = NULL;
    $img->height = NULL;
    $img->alt = NULL;
    $img->class = NULL;
    $img->style = NULL;
    $img->removeAttribute('data-picture-mapping');
    $img->removeAttribute('data-aspectratio');
    // Replace src with data-srcset, if not set
    if ($img->hasAttribute('data-srcset') != null && !isset($img->src)) {
      $img->src = explode(' ', $img->getAttribute('data-srcset'), 2)[0];
      $img->removeAttribute('data-srcset');
    }
    // Replace src with srcset, if not set
    if (isset($img->srcset) && !isset($img->src)) {
      $img->src = $img->srcset;
    }
    $img->srcset = NULL;
    // Remove url parameters from src
    $img->src = strtok($img->src, '?');
    // Set title if needed
    if (isset($img->title)) {
      $title = $img->title;
      $img->title = NULL;
      $img->outertext = $img->outertext . '<figcaption>' . $title . '</figcaption>';
    }
    $img->outertext = '<figure>' . $img->outertext . '</figure>';
  }
  // Remove all unneeded attributes
  foreach ($html->find('[id]') as $e) {
    $e->id = NULL;
  }
  foreach ($html->find('[class]') as $e) {
    $e->class = NULL;
  }
  foreach ($html->find('[style]') as $e) {
    $e->style = NULL;
  }

  $processed_value = $html->save();

  $variables['elements'][0]['key'] = 'content:encoded';
  $variables['elements'][0]['value'] = $processed_value;
}
