<?php 

/**
 * Implements hook_help.
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function bel_currency_help($path, $arg) {
  switch ($path) {
  case "admin/help#bel_currency":
    return '<p>'.t("Displays current currency").'</p>';
    break;
  }
}

/** 
 * Implements hook_block_info().
 */
function bel_currency_block_info() {
  $blocks['bel_currency'] = 
    array('info' => t('Currency'), 
	  'cache' => DRUPAL_CACHE_PER_ROLE);
  return $blocks;
}

/**
 * Custom parser function
 */
function bel_currency_download_data() {
  $aCurrencyName = array("USD","EUR","RUB"); 
  $today = date("m/d/y");

  $feed = "http://www.nbrb.by/Services/XmlExRates.aspx?ondate=$today";
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $feed);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
  $output = curl_exec($ch);
  curl_close($ch);

  $xml = simplexml_load_string($output);

  $isFirst = true;
  $answer = '';
  foreach ($xml->Currency as $item) {     
    if (in_array($item->CharCode, $aCurrencyName)) {
      $curRate = floatval($item->Rate); 
      if (!$isFirst) {
	$answer .= '<span class="bel-currency-delimiter">'.'|'.'</span>';
      }
      $answer .= '<span class="bel-currency-row">';
      $answer .= '<span class="bel-currency-char">'.$item->CharCode.'</span>';
      $answer .= '<span class="bel-currency-num">'.number_format($curRate,2,'.','').'</span>';
      $answer .= '</span>'; 
      $isFirst = false;
    }
  }
  return $answer;
}

/**
 * Display result
 */
function bel_currency_block_view($delta = '') {
  switch($delta){
  case 'bel_currency':
    $block['subject'] = t('Currency');
    if(user_access('access content')){  
      $cache = cache_get('bel_currency_info', 'cache');
      if ($cache) {
	$result = $cache->data; }
      else {
	$result = bel_currency_download_data(); // Use our function for getting result
	cache_set('bel_currency_info', $result, 'cache', 43200);
      }
      if (empty($result)) {
	$block['content'] = '';
      } else {
	$block['content'] = $result;
      }
    }
  }
  return $block;
}
