<?php

/**
 * @file
 * (Un)installation functions for Views RSS: Google Discover Elements module.
 */

/**
 * Implements hook_install().
 */
function views_rss_google_discover_install() {
  cache_clear_all('views_rss:', 'cache_views', TRUE);
}

/**
 * Implements hook_uninstall().
 */
function views_rss_google_discover_uninstall() {
  if (db_table_exists('cache_views')) {
    cache_clear_all('views_rss:', 'cache_views', TRUE);
  }
}
