<?php
/**
 * @file
 * Cackle social comments.
 */

/**
 * Implements hook_help().
 */
function cackle_help($path, $arg) {
  switch ($path) {
    case "admin/help#cackle":
      return '<div><h1>Installation</h1>' . '<p>' . t("1. Upload  folder `cackle` to the `drupal\sites\all\modules` directory") . '</p>' . '<p>' . t("2. Enable Cackle in drupal's admin") . '</p>' . '<p>' . t("3. Register your site at cackle.me") . '</p>' . '<p>' . t("4. Enter siteId and api Keys in Configuration/Web services/Cackle comments confuguration from cackle.me") . '</p>' . t("5. Select 'Content' region for Cackle in drupal's admin (Structure=>Blocks)") . '</p>' . '<p>' . t("6. In Cofiguration => Performance => Clear all caches") . '</p>';
      break;
  }
}
/**
 * Implements hook_block_info().
 */
function cackle_block_info() {
  // The name that will appear in the block list.
  $blocks['cackle'] = array('info' => t('Cackle'), 'cache' => DRUPAL_CACHE_PER_ROLE);
  return $blocks;
}
/**
 * Loading external lib and starting comments sync.
 */
function cackle_in() {
  module_load_include('php', 'cackle', 'cackle');
  $a = new Cackle();
  $template = $a->cackleDisplayComments();
  return $template;
}
/**
 * Initializing cackle's module.
 */
function cackle_block_view($delta = '') {
  switch ($delta) {
    case 'cackle':
      $mc_site = variable_get('cackle_mc_site', 1);
      $nid = arg(1);
      $node = node_load($nid);
      $node_type = '';
      if (node_type_get_type($node)) {
        $node_type = node_type_get_type($node)->type;
      }
      if ($node_type == "article" || $node_type == "page" || $node_type == "forum") {
        if (arg(0) != "forum") {
          $dc = cackle_in();
          $block['content'] = $dc;
        }
        else {
          $block['content'] = '';
        }
      }
      else {
        $block['content'] = '';
      }
  }
  return $block;
}
/**
 * Adding counter's js function.
 */
function cackle_output_footer_comment_js() {
  ob_start();?>
  var mcSite = '<?php echo variable_get('cackle_mc_site', NULL) ?>';
  (function() {
    var mc = document.createElement('script');
    mc.type = 'text/javascript'; 
    mc.async = true;
    mc.src = 'http://cackle.me/mc.count-min.js';
    (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(mc); 
  })();
  <?php return $debug = ob_get_clean();
}
/**
 * Adding counter's link #mc-container for the node.
 */
function cackle_node_view($node, $view_mode) {
  drupal_add_js(cackle_output_footer_comment_js(), array(
    'type' => 'inline',
    'scope' => 'footer',
    'weight' => 5,
  ));
  switch ($view_mode) {
    case 'teaser':
      $links['cackle_comments_num'] = array(
        'title' => t('Comments'),
        'href' => 'node/' . $node->nid,
        'fragment' => 'mc-container',
        'attributes' => array(
          'cackle-channel' => $node->nid,
        ),
      );
      $node->content['links']['cackle'] = array(
        '#theme' => 'links',
        '#links' => $links,
        '#attributes' => array(
          'class' => array('links', 'inline'),
        ),
      );
      break;
  }
}
/**
 * Implements hook_menu().
 */
function cackle_menu() {
  $items = array();

  $items['admin/config/services/cackle'] = array(
    'title' => 'Cackle comments configuration',
    'description' => 'Configuration for Cackle module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cackle_admin_settings'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
    'file' => 'cackle.admin.inc',
  );

  return $items;
}
